tracker_type: bytetrack

# ByteTrack settings
track_high_thresh: 0.5  # Lowered to help initiate tracks on less confident detections
track_low_thresh: 0.1
new_track_thresh: 0.6
track_buffer: 20        # Increased to give the tracker more "memory"
match_thresh: 0.7

# CMC MOT Challenge settings
gmc_method: null

# ReID settings
reid_model: null
reid_verbose: True
fuse_score: false       # This parameter is required by the library